default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.2
    hooks:
      - id: clang-format
